spring:
    application:
        name: simple
    datasource:
        url: jdbc:postgresql://localhost:5432/simple
        username: postgres
        password: leye
        driver-class-name: org.postgresql.Driver
    jpa:
        hibernate:
            ddl-auto: update
        show-sql: true
server:
  port: 8080